#' Import graph data
#'
#' @param tsv_filepath file path to tsv document generated by copying graph data from pimsoft.
#'
#' @return returns a tsv df, adapted for incorporation to ggplot graph.
#' @export
#'
tsv_import <- function(tsv_filepath) {

tsvdf <- read_tsv(tsv_filepath)

long_tsvdf <- tsvdf %>%
  pivot_longer(
    cols = 3:5,
    names_to = "ROI",
    values_to = "Value"
  )

return(long_tsvdf)
}
